version: '3.7'

services:
  db:
    image: postgres:13
    container_name: myapp-postgres-13
    volumes:
      - pg_data:/var/lib/postgresql/data
    command: "postgres -c 'max_connections=500'"
    environment:
      POSTGRES_DB: your_database_name
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "rails db:migrate && rm tmp/pids/server.pid; bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      DB_HOST: db
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    depends_on:
      - db

volumes:
  pg_data:

networks:
  default:
    name: school_api_default
